FROM jenkins/jenkins:lts
USER root

# install docker cli
RUN apt-get update && apt-get install -y docker.io

# install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

# install python
RUN apt-get install -y python3 python3-pip

USER jenkins